### ISSUE TITLE
Decimals are left out from activation

### ISSUE THREAD

**Issue by jolappi** [elleracompany/commerce-klarna-checkout#38]
There is an issue that in Klarna only part of the order is activated if there is decimal in amount.
ex. item cost 5,30€ gets activated only for 5€.
If you change KlarnaCheckout.php line 724 like this
'captured_amount' => (int)($order->getTotal()*100),//$transaction->paymentAmount * 100,
then it will capture the whole amount but I think this is not proper fix and should be probably fixed to somewhere else.

**Comment by jellingsen** [comment]
Hi,

Thank you for reporting this. This was indeed a typecast error.
Klarna expects amounts in minor units (cents) while Craft Commerce works with decimal.

We need to use the $transaction->paymentAmount since this is the amount requested to be captured from the user in the admin panel. We just need to do the multiplication first, before casting it to an integer.

This should now be fixed in v1.1.12
