### ISSUE TITLE
Double klarna orders

### ISSUE THREAD

**Issue by wilmer05** [elleracompany/commerce-klarna-checkout#51]
Hello,

sometimes I get 2 orders in klarna that are same order in craft CMS.

From the logs I have for example:

`2021-04-06 23:56:37 Created order 235d1537a0319f2d1588a980f40dc562 (232973)`
`2021-04-07 00:02:05 Created order 235d1537a0319f2d1588a980f40dc562 (232973)`
`2021-04-07 00:05:28 Updated order 235d1537a0319f2d1588a980f40dc562 (232973)`

That's really bad because then I have two different orders with two different Ids but in Craft CMS I just have one.

**Comment by jellingsen** [comment]
Hi,

So this will happen if a user renders the Klarna widget several times. Ex. going to the payment page, going back to the cart, and then back to the payment page again. We need to register an order to get the klarna widget, and I have encountered that issue while developing. 

I did not expect that it could create issues for order management.

I'll look into if we can save the widget in a session or something, so that we don't have to register separate orders with klarna.

**Comment by wilmer05** [comment]
Thanks, Yes Exactly that is the way one can reproduce the error.

I tried overriding the plugin class and doing updates on the order you create on the first authorize by using the same reference of the order but at some point that temporal order turns to be READ_ONLY and fails after some time to update
